### ISSUE TITLE
How to implement memory alias

### ISSUE THREAD

**Issue by 98hq** [luci-project/luci#1]
This work is great.
I have some questions about the implementation of memory aliases.
For example, I now have two versions of a dynamic library, A and B.
When the program is running, dynamic library A has been loaded into memory, and its data segment is based on the private mapping of the dynamic library file.
When I want the program to call a function in dynamic library B, how can the data segment of dynamic library B share the same physical memory as the data segment of dynamic library A?

My personal understanding is that the content of the data segment of dynamic library A needs to be stored in the file created by memfd_create first, and then the data area of ​​dynamic library A is munmapped. Then the file created by memfd_create is mapped to two fixed memory addresses to achieve physical memory sharing. However, if this is done, when viewing the program layout through the /proc file system, the data segment of the dynamic library is actually shared.

In addition, I would like to know if LUCI cannot modify the read-only GOT table of the program when the program that depends on this dynamic library is compiled and linked with FULL_RELRO enabled, or will it modify the permissions of the memory area through mprotect before making the modification.

**Comment by thelazt** [comment]
You are right, by default the data mapping of a library is private.
However, this can easily be changed.
Luci will decide on load time if the data segment should be shared, and if so, create a shared mapping at the designated address, before copying the file contents, see [MemorySegment::map](https://github.com/luci-project/luci/blob/d8a17c480ca177c6fa000190bdb1ff20c1aa3c4e/src/memory_segment.cpp#L48).
But it is also possible to do it afterwards, by unmapping the data segment, as it is done in the [live.so project](https://github.com/luci-project/live.so/blob/9345f74e1a9ca8b5f73764e0b87d85de779ce44f/live.c#L222C1-L223C119) (and implemented in [MemorySegment::shmemdup](https://github.com/luci-project/luci/blob/d8a17c480ca177c6fa000190bdb1ff20c1aa3c4e/src/memory_segment.cpp#L280C5-L280C30) for `fork()`).

In fact, it is neither necessary to explicitly do the unmap (`MAP_FIXED` will replace the memory) nor alias the whole data segment.
You can do it on page granularity in your process as well, as this example demonstrates:
```c
#define _GNU_SOURCE
#include <sys/mman.h>
#include <stdlib.h>
#include <stdio.h>
#include <unistd.h>

#define PAGE_SZ 4096
long int x __attribute__ ((aligned(PAGE_SZ))) = 23;  // x will have its own page
long int y __attribute__ ((aligned(PAGE_SZ))) = 42;
long int z __attribute__ ((aligned(PAGE_SZ))) = 99;

static void remap(void * addr, size_t size, int fd) {
	if (munmap(addr, size) == -1) {
		perror("munmap");
		exit(EXIT_FAILURE);
	} else if (mmap(addr, size, PROT_READ | PROT_WRITE, MAP_SHARED | MAP_FIXED_NOREPLACE, fd, 0) != addr) {
		perror("mmap");
		exit(EXIT_FAILURE);
	}
}

int main(void) {
	// Create memfd & resize to page size
	int memfd = memfd_create("shared", 0);
	if (memfd == -1) {
		perror("memfd");
		return EXIT_FAILURE;
	} else if (ftruncate(memfd, PAGE_SZ) == -1) {
		perror("ftruncate");
		return EXIT_FAILURE;
	}

	// Show original contents
	printf("x = %ld @ %p\n",   x, &x);  // x = 23
	printf("y = %ld @ %p\n",   y, &y);  // y = 42
	printf("z = %ld @ %p\n\n", z, &z);  // z = 99

	// Remap x to shared memory
	remap(&x, PAGE_SZ, memfd);
	printf("x = %ld @ %p\n",   x, &x);  // x = 0 (due to ftruncate)
	printf("y = %ld @ %p\n\n", y, &y);  // y = 42

	// Remap y to shared memory
	remap(&y, PAGE_SZ, memfd);
	// Now if one variable is changed, the other will be changed as well, due to aliasing
	x = 1337;
	printf("x = %ld @ %p\n",   x, &x);  // x = 1337
	printf("y = %ld @ %p\n\n", y, &y);  // y = 1337

	y = 7;
	printf("x = %ld @ %p\n",   x, &x);  // x = 7
	printf("y = %ld @ %p\n\n", y, &y);  // y = 7

	// Without remapping z still remains unchanged
	printf("z = %ld @ %p\n\n", z, &z);  // z = 99

	// But z it can be remapped as well:
	remap(&z, PAGE_SZ, memfd);
	z = 29;
	printf("x = %ld @ %p\n",   x, &x);  // x = 29
	printf("y = %ld @ %p\n",   y, &y);  // y = 29
	printf("z = %ld @ %p\n\n", z, &z);  // z = 29

	return EXIT_SUCCESS;
}
```
The output of the example is
```
$ gcc example.c && ./a.out
x = 23 @ 0x562d5f1a5000
y = 42 @ 0x562d5f1a6000
z = 99 @ 0x562d5f1a7000

x = 0 @ 0x562d5f1a5000
y = 42 @ 0x562d5f1a6000

x = 1337 @ 0x562d5f1a5000
y = 1337 @ 0x562d5f1a6000

x = 7 @ 0x562d5f1a5000
y = 7 @ 0x562d5f1a6000

z = 99 @ 0x562d5f1a7000

x = 29 @ 0x562d5f1a5000
y = 29 @ 0x562d5f1a6000
z = 29 @ 0x562d5f1a7000
```
and the memory map (right before remapping the memory for `z`) looks like
```
562d5f19f000-562d5f1a0000 r--p 00000000 08:01 4457192      /path/to/a.out   <-- ELF header
562d5f1a0000-562d5f1a1000 r-xp 00001000 08:01 4457192      /path/to/a.out   <-- executable code
562d5f1a1000-562d5f1a2000 r--p 00002000 08:01 4457192      /path/to/a.out   <-- read-only data
562d5f1a2000-562d5f1a3000 r--p 00002000 08:01 4457192      /path/to/a.out   <-- relocation read-only
562d5f1a3000-562d5f1a5000 rw-p 00003000 08:01 4457192      /path/to/a.out   <-- other variables
562d5f1a5000-562d5f1a6000 rw-s 00000000 00:01 17426        /memfd:shared    <-- x
562d5f1a6000-562d5f1a7000 rw-s 00000000 00:01 17426        /memfd:shared    <-- y
562d5f1a7000-562d5f1a8000 rw-p 00007000 08:01 4457192      /path/to/a.out   <-- z (not yet shared!)
562d75b5f000-562d75b80000 rw-p 00000000 00:00 0            [heap]
```
You might also want to have a look at this abstract [visualization](https://sys.cs.fau.de/publications/2023/heinloth_23_atc-poster.pdf).

For your second question regarding full RELRO: Luci will simply adjust the protection via `mprotect` as you already expected.
This is also done in the same file, see [MemorySegment::finalize](https://github.com/luci-project/luci/blob/d8a17c480ca177c6fa000190bdb1ff20c1aa3c4e/src/memory_segment.cpp#L160).

**Comment by 98hq** [comment]
Thank you for your prompt reply. I have a few questions about your reply.

> In fact, it is neither necessary to explicitly do the unmap (`MAP_FIXED` will replace the memory) nor alias the whole data segment.

When using MAP_FIXED before replacing the mapped memory area, is it necessary to store the data of the mapped memory area into the file created by memfd_create?

In addition, according to my own test, when using MAP_FIXED's mmap to replace the data segment of the program, the file name of its memory area will change to a file starting with /memfd:, as shown in the figure below.

![image](https://github.com/user-attachments/assets/e3079f1f-8fdb-4bdc-97fe-e44e42625f11)

> Luci will decide on load time if the data segment should be shared, and if so, create a shared mapping at the designated address, before copying the file contents, see [MemorySegment::map](https://github.com/luci-project/luci/blob/d8a17c480ca177c6fa000190bdb1ff20c1aa3c4e/src/memory_segment.cpp#L48).

After reading the source code of memory_segment.cpp, I found that mmap uses MAP_FIXED_NOREPLACE, which means that the memory area where the data is located needs to be munmapped first, and then the file created by memfd_create is mapped to the memory area where the data is located. I don't know if my understanding is accurate?

If the process is like this, there may be a potential problem.
If the program is not compiled with FULL RELRO, when the munmap function is used to unmap the data segment containing the GOT, the subsequent mmap function needs to rely on the content of the GOT table when executing, but at this time the memory area where the GOT table is located has been munmapped, which will cause the program to crash when executing the mmap function. I want to know how you solve this problem?

![image](https://github.com/user-attachments/assets/686eebed-6cb1-412b-8ada-5a4f89bb760e)

In [demo.gif](https://github.com/luci-project/luci/raw/d8a17c480ca177c6fa000190bdb1ff20c1aa3c4e/demo.gif), after the source code of the executable program is modified, the execution result of the program will also change accordingly.
This is very cool, but I have some questions about it.
In demo.gif, after the source code of the executable program is modified, the execution result of the program will also change accordingly.

Does the executable program have to be compiled using PIE? My personal understanding is that only PIE-compiled programs can be loaded into any address in memory.

In addition, is there any difference in the process of loading PIE programs and dynamic libraries? Can you tell me in which file the relevant source code is located?
My understanding is that the executable code segment of the program is loaded into memory, and no other operations are performed, such as parameter setting, constructor execution, etc.

Finally, thank you again for your prompt response. This work is really great.

**Comment by thelazt** [comment]
After creating a new memory area with `memfd_create`, it is expanded with `ftruncate`, thus filling its contents to zero up to the given size.
This is the reason why `x = 0` in the example above after remapping to the address of `x` (via `mmap`).
And then any change to this memory (e.g. by assigning a different value to `x`) will be reflected in this memory mapping and all other mappings of the same physical memory.

So if you want to replace a private mapping with a shared alias, you have to do the following steps:
1. use `memfd_create` to create a new memory area and `ftruncate` it to the desired size.
2. use `mmap` without `MAP_FIXED` to temporarily map it to an unused area in your address space.
3. copy the contents of the target area you want to replace later to the newly mapped area
4. replace/remap your target area with the shared memory.

In the example above, you can do this right after printing the original content as follows:
```c
	// Map to some unused area
	void * tmp_addr = mmap(0, PAGE_SZ, PROT_READ | PROT_WRITE, MAP_SHARED, memfd, 0);
	if (tmp_addr == MAP_FAILED) {
		perror("mmap");
		exit(EXIT_FAILURE);
	}
	printf("tmp_addr @ %p\n", tmp_addr);
	// Copy the contents of page containing x
	memcpy(tmp_addr, &x, PAGE_SZ);

	// Remap x to shared memory
	remap(&x, PAGE_SZ, memfd);
	printf("x = %ld @ %p\n",   x, &x);  // x = 23
```
`tmp_addr` will most likely be in a completely different part of the virtual address space, for example starting with `0x7ef...`.

This is effectively what is done for the GOT / all writable data segment, so the shared mapping will have the contents of the data segment right after loading.

It is worth noting that the "file" of `memfd_create` is quite different from a regular file: the name `/memfd:shared` does not refer to an inode on your filesystem.
In fact, these names don't have to be unique, it is possible to have several different memfd created anonymous files with the same name.
So the name shown in `/proc/.../maps` is only there for debugging purposes.

> Does the executable program have to be compiled using PIE? My personal understanding is that only PIE-compiled programs can be loaded into any address in memory.

Regarding the requirements for updating a file:
Yes, you need to use position-independent code for the approach to work, which includes PIE for executable, so that Luci can place the update version at a different address.
This avoids problems that would occur when changing the mapping of the (currently executed) code.

In general, dynamic shared objects/libraries (which always need PIC) and position independent executables (PIE) are almost the same.
If I remember correctly, glibc `dlopen` checks for the PIE flag in the .DYNAMIC section to prevent loading an executable.
But Luci treats both the same, have a look at `src/object/dynamic.cpp`.

> My understanding is that the executable code segment of the program is loaded into memory, and no other operations are performed, such as parameter setting, constructor execution, etc.

In order to prepare either a library or an executable, there are several steps beyond loading the executable code segment, for example, the thread local storage (TLS) must be prepared, and the initialization functions must be executed (which will execute global constructors) before jumping to the entry point.
However, no adjustments are made to the executable segment itself, it is not writable (which is quite important due to [W^X](https://en.wikipedia.org/wiki/W%5EX)).


And thanks, glad you like the project :)

**Comment by 98hq** [comment]
> ```c
> static void remap(void * addr, size_t size, int fd) {
> 	if (munmap(addr, size) == -1) {
> 		perror("munmap");
> 		exit(EXIT_FAILURE);
> 	} else if (mmap(addr, size, PROT_READ | PROT_WRITE, MAP_SHARED | MAP_FIXED_NOREPLACE, fd, 0) != addr) {
> 		perror("mmap");
> 		exit(EXIT_FAILURE);
> 	}
> }
> ```


> If the process is like this, there may be a potential problem.
> If the program is not compiled with FULL RELRO, when the munmap function is used to unmap the data segment containing the GOT, the subsequent mmap function needs to rely on the content of the GOT table when executing, but at this time the memory area where the GOT table is located has been munmapped, which will cause the program to crash when executing the mmap function. I want to know how you solve this problem?

Thank you for your prompt reply. Suppose I want to share the data segment of the executable program. In the `remap` function above, after `munmap(addr, size)` is executed, the data segment of the executable program containing the `GOT` table is unmapped. The subsequent `mmap(addr, size, PROT_READ | PROT_WRITE, MAP_SHARED | MAP_FIXED_NOREPLACE, fd, 0) `statement will get the jump address from the `GOT`, but the `GOT` is unmapped at this time, so executing this function will crash. Only after the function is successfully executed will the data segment of the executable file restore its normal content. My question is how to ensure the successful execution of `mmap`. Can this problem be solved by storing the address of `mmap` in a function pointer and then calling `mmap` through the function pointer?

**Comment by thelazt** [comment]
Ah, sorry, I think I get your point now: Calling `mmap` while the GOT is currently unmapped.

Well, this is not a problem for Luci, since it is a self-contained dynamic linker/loader.
Luci does not use glibc, but its own tiny libc called [DLH](https://github.com/luci-project/dlh/), which is statically linked.
Accordingly, a `mmap` call in Luci does not use the GOT, but jumps directly to the function that executes the `syscall`.

You can also just use `MAP_FIXED` to avoid unmapping.
But you have to do a copy using the temporary memory area first.
For example, this revised function will first copy the original content to shared memory via a temporary mapping.
Then it atomically replaces the original mapping with the shared one, which now has the same contents.
```c
static void remap(void * addr, size_t size, int fd) {
	// duplicate memory via temporary area
	void * tmp_addr = mmap(0, size, PROT_READ | PROT_WRITE, MAP_SHARED, fd, 0);
	if (tmp_addr == MAP_FAILED) {
		perror("mmap tmp");
		exit(EXIT_FAILURE);
	}
	memcpy(tmp_addr, addr, size);
	if (munmap(tmp_addr, size) == -1) {
		perror("munmaptmp");
		exit(EXIT_FAILURE);
	}

	// Remap the target address (without unmapping it)
	if (mmap(addr, size, PROT_READ | PROT_WRITE, MAP_SHARED | MAP_FIXED, fd, 0) != addr) {
		perror("mmap");
		exit(EXIT_FAILURE);
	}
}
```
This is effectively the approach taken by [live.so](https://github.com/luci-project/live.so).

Theoretically, a function pointer to `mmap` could work, but I would rather suggest playing it safe and atomically remap the already prepared shared memory.

**Comment by 98hq** [comment]
Thank you for your prompt reply.

This work is great. The core of it is to load the updated version of the dynamic library into memory, and then share the data segment of the updated version of the dynamic library with the data segment of the original library, so that the call to other external library functions can be controlled by updating the GOT table.
In addition, find other dynamic libraries that depend on the updated library, and then update their GOT tables so that they can jump to the updated dynamic library for execution during subsequent execution.
I hope my overall understanding of this work is correct.

I have a question about this. Why create a new memory segment to store the updated dynamic library?
I think there is another way: use the `mmap` function to load the updated version of the dynamic library and replace the code and read-only segment of the original version of the dynamic library.
Have you considered this method? Or does this method have hidden dangers or risks that I haven't considered?

**Comment by thelazt** [comment]
Yes, the procedure you describe is correct.

Updating the code segment in-place is very difficult:
While you can patch some instructions (and Luci does in some special cases), this is not a good way to replace the whole segment.
The compiler might rearrange the layout (e.g. by inserting a new call to a glibc library function, for which the compiler creates a new stub in PLT), and then the address pointed to by the instruction pointer (`rip`) would contain something completely different.
Especially for x86/x64 with variable instruction length, it is quite likely that you would crash right after an update with an illegal opcode.
This is true even if the compiler produces the same layout and only the function you are executing has changed:
Even if you are lucky and the `rip` points to a valid instruction, you cannot be sure that the context (stack, register allocation) matches the previous version.
I can recommend to make some changes in simple programs and compare the address offsets in the ELF via `objdump` - it is quite interesting how small changes like introducing a new bounds check (which is not uncommon for security fixes) change the layout, especially if optimizations are enabled.

**Comment by 98hq** [comment]
Thanks for your reply. You are right; updating the code segment in-place is indeed complex and difficult.
